use super::*;

pub(super) fn render_kiro_module(collector: &Collector) -> String {
    let mut lines = vec![
        "// Generated by `kiro host gen`; edit the Rust manual section for fallbacks.".to_string(),
    ];
    if !collector.records.is_empty() {
        for (name, record) in &collector.records {
            lines.push(String::new());
            lines.push(format!("struct {} {{", name));
            for field in &record.fields {
                lines.push(format!(
                    "    {}: {}",
                    field.name,
                    kiro_type(&field.rust_type)
                ));
            }
            lines.push("}".to_string());
        }
    }
    if !collector.handles.is_empty() {
        lines.push(String::new());
        for handle in &collector.handles {
            lines.push(format!("handle {}", handle));
        }
    }
    if !collector.bindings.is_empty() {
        lines.push(String::new());
        for binding in &collector.bindings {
            let pure = if binding.pure { "pure " } else { "" };
            let params = binding
                .params
                .iter()
                .map(|p| format!("{}: {}", p.name, kiro_type(&p.rust_type)))
                .collect::<Vec<_>>()
                .join(", ");
            let bang = if binding.can_error { "!" } else { "" };
            lines.push(format!(
                "{}rust fn {}({}) -> {}{}",
                pure,
                binding.exported_name,
                params,
                kiro_type(&binding.return_type),
                bang
            ));
        }
    }
    lines.push(String::new());
    lines.join("\n")
}

pub(super) fn render_rust_glue(collector: &Collector) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_BEGIN);
    out.push_str("\n\n");
    for binding in &collector.bindings {
        out.push_str(&render_binding_glue(binding, collector));
        out.push('\n');
    }
    if !collector.skipped.is_empty() {
        out.push_str("// Skipped unsupported Rust APIs:\n");
        for skipped in &collector.skipped {
            out.push_str(&format!("// - {}\n", skipped));
        }
        out.push('\n');
    }
    out.push_str(GENERATED_END);
    out.push('\n');
    out
}

fn render_binding_glue(binding: &Binding, collector: &Collector) -> String {
    let async_kw = if binding.pure { "" } else { "async " };
    let mut body = String::new();
    body.push_str(&format!(
        "pub {}fn {}(args: Vec<RuntimeVal>) -> HostResult {{\n",
        async_kw, binding.exported_name
    ));
    body.push_str(&format!(
        "    RuntimeVal::expect_arity(&args, {}, \"{}\")?;\n",
        binding.params.len(),
        binding.exported_name
    ));
    for (idx, param) in binding.params.iter().enumerate() {
        body.push_str(&decode_param(
            binding,
            idx,
            param,
            &binding.exported_name,
            collector,
        ));
    }
    let args = binding
        .params
        .iter()
        .map(|param| param.name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let call = match &binding.source {
        BindingSource::CrateFunction { path } => format!("{}({})", path, args),
        BindingSource::ManualFunction { module, function } => {
            format!("{}::{}({})", module, function, args)
        }
        BindingSource::Constructor { path, .. } => format!("{}({})", path, args),
        BindingSource::Method {
            crate_ident: _,
            method_name,
            receiver_mutable: _,
        } => {
            let receiver = &binding.params[0].name;
            let rest = binding
                .params
                .iter()
                .skip(1)
                .map(|param| param.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            format!("{}.{}({})", receiver, method_name, rest)
        }
    };

    if binding.can_error {
        let err_name = binding.error_name.as_deref().unwrap_or("HostError");
        body.push_str(&format!("    match {} {{\n", call));
        body.push_str(&format!(
            "        Ok(value) => Ok({}),\n",
            encode_value("value", &binding.return_type, collector)
        ));
        body.push_str(&format!(
            "        Err(err) => Err(KiroError::message(\"{}\", err.to_string())),\n",
            err_name
        ));
        body.push_str("    }\n");
    } else {
        match binding.return_type {
            RustType::Void => {
                body.push_str(&format!("    {};\n", call));
                body.push_str("    Ok(RuntimeVal::Void)\n");
            }
            _ => {
                body.push_str(&format!("    let value = {};\n", call));
                body.push_str(&format!(
                    "    Ok({})\n",
                    encode_value("value", &binding.return_type, collector)
                ));
            }
        }
    }
    body.push_str("}\n");
    body
}

fn decode_param(
    binding: &Binding,
    idx: usize,
    param: &Param,
    fn_name: &str,
    collector: &Collector,
) -> String {
    let arg = format!("RuntimeVal::expect_arg(&args, {}, \"{}\")?", idx, fn_name);
    match &param.rust_type {
        RustType::Str => format!("    let {} = {}.as_str()?.to_string();\n", param.name, arg),
        RustType::Bytes { borrowed: true } => {
            format!("    let {} = {}.as_bytes()?;\n", param.name, arg)
        }
        RustType::Bytes { borrowed: false } => {
            format!("    let {} = {}.as_bytes()?.to_vec();\n", param.name, arg)
        }
        RustType::Num { rust } if rust == "f64" => {
            format!("    let {} = {}.as_num()?;\n", param.name, arg)
        }
        RustType::Num { rust } if rust == "f32" => {
            format!("    let {} = {}.as_num()? as f32;\n", param.name, arg)
        }
        RustType::Num { rust } => {
            format!("    let {} = {}.as_num()? as {};\n", param.name, arg, rust)
        }
        RustType::Bool => format!("    let {} = {}.as_bool()?;\n", param.name, arg),
        RustType::Record(type_name) => decode_record_param(&param.name, &arg, type_name, collector),
        RustType::Handle(type_name) if collector.mutable_handles.contains(type_name) => {
            let mutable = matches!(
                binding.source,
                BindingSource::Method {
                    receiver_mutable: true,
                    ..
                }
            ) && idx == 0;
            let mutability = if mutable { "mut " } else { "" };
            format!(
                "    let {mutability}{} = {}.as_handle(\"{}\")?.downcast_ref::<std::sync::Mutex<{}>>().ok_or_else(|| KiroError::message(\"TypeError\", \"expected mutable handle payload {}\"))?.lock().map_err(|_| KiroError::message(\"HandlePoisoned\", \"{} handle lock was poisoned\"))?;\n",
                param.name,
                arg,
                type_name,
                handle_payload_type(binding, type_name),
                type_name,
                type_name
            )
        }
        RustType::Handle(type_name) => format!(
            "    let {} = {}.as_handle(\"{}\")?.downcast_ref::<{}>().ok_or_else(|| KiroError::message(\"TypeError\", \"expected handle payload {}\"))?;\n",
            param.name,
            arg,
            type_name,
            handle_payload_type(binding, type_name),
            type_name
        ),
        RustType::List(inner) => decode_list_param(&param.name, &arg, inner, collector),
        RustType::Map(inner) => decode_map_param(&param.name, &arg, inner, collector),
        RustType::Void => format!("    let {} = ();\n", param.name),
    }
}

fn decode_list_param(name: &str, arg: &str, inner: &RustType, collector: &Collector) -> String {
    let mut out = format!("    let mut {} = Vec::new();\n", name);
    out.push_str(&format!("    for item in {}.as_list()? {{\n", arg));
    out.push_str(&format!(
        "        {}.push({});\n",
        name,
        decode_runtime_expr("item", inner, collector)
    ));
    out.push_str("    }\n");
    out
}

fn decode_map_param(name: &str, arg: &str, inner: &RustType, collector: &Collector) -> String {
    let mut out = format!("    let mut {} = std::collections::HashMap::new();\n", name);
    out.push_str(&format!("    for (key, value) in {}.as_map()? {{\n", arg));
    out.push_str(&format!(
        "        {}.insert(key.clone(), {});\n",
        name,
        decode_runtime_expr("value", inner, collector)
    ));
    out.push_str("    }\n");
    out
}

fn decode_runtime_expr(value: &str, ty: &RustType, collector: &Collector) -> String {
    match ty {
        RustType::Str => format!("{}.as_str()?.to_string()", value),
        RustType::Bytes { .. } => format!("{}.as_bytes()?.to_vec()", value),
        RustType::Num { rust } if rust == "f64" => format!("{}.as_num()?", value),
        RustType::Num { rust } => format!("{}.as_num()? as {}", value, rust),
        RustType::Bool => format!("{}.as_bool()?", value),
        RustType::Record(type_name) => decode_record_expr(value, type_name, collector),
        _ => {
            "return Err(KiroError::message(\"TypeError\", \"unsupported nested type\"))".to_string()
        }
    }
}

fn decode_record_param(name: &str, arg: &str, type_name: &str, collector: &Collector) -> String {
    format!(
        "    let {} = {};\n",
        name,
        decode_record_expr(arg, type_name, collector)
    )
}

fn decode_record_expr(value: &str, type_name: &str, collector: &Collector) -> String {
    let record = collector
        .records
        .get(type_name)
        .expect("record Rust type must have a definition");
    let fields = record
        .fields
        .iter()
        .map(|field| {
            let value = format!(
                "__kiro_fields.get(\"{}\").ok_or_else(|| KiroError::message(\"TypeError\", \"missing {}.{}\"))?",
                field.name, type_name, field.name
            );
            format!(
                "{}: {}",
                field.name,
                decode_runtime_expr(&value, &field.rust_type, collector)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "{{ let __kiro_fields = {}.as_struct(\"{}\")?; {}::{} {{ {} }} }}",
        value, type_name, collector.crate_ident, type_name, fields
    )
}

fn encode_value(name: &str, ty: &RustType, collector: &Collector) -> String {
    match ty {
        RustType::Void => "RuntimeVal::Void".to_string(),
        RustType::Handle(type_name) if collector.mutable_handles.contains(type_name) => format!(
            "RuntimeVal::handle(\"{}\", std::sync::Mutex::new({}))",
            type_name, name
        ),
        RustType::Handle(type_name) => format!("RuntimeVal::handle(\"{}\", {})", type_name, name),
        _ => encode_inner_value(name, ty, collector),
    }
}

fn encode_inner_value(name: &str, ty: &RustType, collector: &Collector) -> String {
    match ty {
        RustType::Str | RustType::Bool => format!("RuntimeVal::from({})", name),
        RustType::Bytes { .. } => format!("RuntimeVal::bytes({})", name),
        RustType::Num { .. } => format!("RuntimeVal::from({} as f64)", name),
        RustType::List(inner) => format!(
            "RuntimeVal::List({}.into_iter().map(|v| {}).collect())",
            name,
            encode_inner_value("v", inner, collector)
        ),
        RustType::Map(inner) => format!(
            "RuntimeVal::Map({}.into_iter().map(|(k, v)| (k, {})).collect())",
            name,
            encode_inner_value("v", inner, collector)
        ),
        RustType::Record(type_name) => {
            let record = collector
                .records
                .get(type_name)
                .expect("record Rust type must have a definition");
            let fields = record
                .fields
                .iter()
                .map(|field| {
                    format!(
                        "(\"{}\".to_string(), {})",
                        field.name,
                        encode_inner_value(
                            &format!("{}.{}", name, field.name),
                            &field.rust_type,
                            collector,
                        )
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!(
                "RuntimeVal::structure(\"{}\", [{}].into_iter().collect())",
                type_name, fields
            )
        }
        RustType::Handle(type_name) => format!("RuntimeVal::handle(\"{}\", {})", type_name, name),
        RustType::Void => "RuntimeVal::Void".to_string(),
    }
}

fn kiro_type(ty: &RustType) -> String {
    match ty {
        RustType::Str => "str".to_string(),
        RustType::Bytes { .. } => "bytes".to_string(),
        RustType::Num { .. } => "num".to_string(),
        RustType::Bool => "bool".to_string(),
        RustType::Void => "void".to_string(),
        RustType::List(inner) => format!("list {}", kiro_type(inner)),
        RustType::Map(inner) => format!("map str {}", kiro_type(inner)),
        RustType::Record(name) | RustType::Handle(name) => name.clone(),
    }
}

pub(super) fn initial_rust_module(manual_module: &str) -> String {
    format!(
        r#"mod {manual_module} {{
    use super::*;
    use kiro_macros::{{kiro_export, kiro_handle, kiro_struct}};
    use std::collections::HashMap;
}}

// kiro:generated begin
// kiro:generated end
"#
    )
}

pub(super) fn replace_generated_region(existing: &str, generated: &str) -> String {
    let Some(start) = existing.find(GENERATED_BEGIN) else {
        let mut out = existing.trim_end().to_string();
        out.push_str("\n\n");
        out.push_str(generated);
        return out;
    };
    let Some(end_rel) = existing[start..].find(GENERATED_END) else {
        let mut out = existing[..start].trim_end().to_string();
        out.push_str("\n\n");
        out.push_str(generated);
        return out;
    };
    let end = start + end_rel + GENERATED_END.len();
    let mut out = String::new();
    out.push_str(existing[..start].trim_end());
    out.push_str("\n\n");
    out.push_str(generated.trim_end());
    out.push('\n');
    out.push_str(existing[end..].trim_start_matches('\n'));
    out
}
