use super::*;

pub(super) fn render_kiro_module(collector: &Collector) -> String {
    let mut lines = vec![
        "// Generated by `kiro host gen`; edit the Rust manual section for fallbacks.".to_string(),
    ];
    if collector.uses_vector_values() {
        lines.extend([
            String::new(),
            "struct VectorValues {".to_string(),
            "    element_type: str".to_string(),
            "    values: list num".to_string(),
            "}".to_string(),
        ]);
    }
    if !collector.records.is_empty() {
        for (name, record) in &collector.records {
            lines.push(String::new());
            lines.push(format!("struct {} {{", name));
            for field in &record.fields {
                lines.push(format!(
                    "    {}: {}",
                    field.name,
                    kiro_type(&field.rust_type)
                ));
            }
            lines.push("}".to_string());
        }
    }
    if !collector.handles.is_empty() {
        lines.push(String::new());
        for handle in &collector.handles {
            lines.push(format!("handle {}", handle));
        }
    }
    if !collector.bindings.is_empty() {
        lines.push(String::new());
        for binding in &collector.bindings {
            let pure = if binding.pure { "pure " } else { "" };
            let params = binding
                .params
                .iter()
                .map(|p| format!("{}: {}", p.name, kiro_type(&p.rust_type)))
                .collect::<Vec<_>>()
                .join(", ");
            let bang = if binding.can_error || binding_uses_one_shot_receiver(binding, collector) {
                "!"
            } else {
                ""
            };
            lines.push(format!(
                "{}rust fn {}({}) -> {}{}",
                pure,
                binding.exported_name,
                params,
                kiro_type(&binding.return_type),
                bang
            ));
        }
    }
    lines.push(String::new());
    lines.join("\n")
}

pub(super) fn render_rust_glue(collector: &Collector) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_BEGIN);
    out.push_str("\n\n");
    if collector.uses_zova_errors() {
        out.push_str(ZOVA_ERROR_HELPER);
        out.push('\n');
    }
    if collector.uses_vector_values() {
        out.push_str(VECTOR_VALUE_HELPERS);
        out.push('\n');
    }
    for binding in &collector.bindings {
        out.push_str(&render_binding_glue(binding, collector));
        out.push('\n');
    }
    if !collector.skipped.is_empty() {
        out.push_str("// Skipped unsupported Rust APIs:\n");
        for skipped in &collector.skipped {
            out.push_str(&format!("// - {}\n", skipped));
        }
        out.push('\n');
    }
    out.push_str(GENERATED_END);
    out.push('\n');
    out
}

fn render_binding_glue(binding: &Binding, collector: &Collector) -> String {
    let async_kw = if binding.pure { "" } else { "async " };
    let mut body = String::new();
    body.push_str(&format!(
        "pub {}fn {}(args: Vec<RuntimeVal>) -> HostResult {{\n",
        async_kw, binding.exported_name
    ));
    body.push_str(&format!(
        "    RuntimeVal::expect_arity(&args, {}, \"{}\")?;\n",
        binding.params.len(),
        binding.exported_name
    ));
    for (idx, param) in binding.params.iter().enumerate() {
        body.push_str(&decode_param(
            binding,
            idx,
            param,
            &binding.exported_name,
            collector,
        ));
    }
    let args = binding
        .params
        .iter()
        .map(call_argument)
        .collect::<Vec<_>>()
        .join(", ");
    let call = match &binding.source {
        BindingSource::CrateFunction { path } => format!("{}({})", path, args),
        BindingSource::ManualFunction { module, function } => {
            format!("{}::{}({})", module, function, args)
        }
        BindingSource::Constructor { path, .. } => format!("{}({})", path, args),
        BindingSource::Method {
            crate_ident: _,
            method_name,
            receiver_mutable: _,
            receiver_consuming: _,
        } => {
            let receiver = &binding.params[0].rust_name;
            let rest = binding
                .params
                .iter()
                .skip(1)
                .map(call_argument)
                .collect::<Vec<_>>()
                .join(", ");
            format!("{}.{}({})", receiver, method_name, rest)
        }
    };

    if binding.can_error {
        let err_name = binding.error_name.as_deref().unwrap_or("HostError");
        body.push_str(&format!("    match {} {{\n", call));
        if let Some(buffer) = &binding.output_buffer {
            body.push_str(&format!(
                "        Ok(copied) => {{ if copied > {buffer}.len() {{ return Err(KiroError::message(\"HostContractError\", \"host wrote beyond its output buffer\")); }} {buffer}.truncate(copied); Ok(RuntimeVal::bytes({buffer})) }},\n"
            ));
        } else {
            let value_name = if binding.return_type == RustType::Void {
                "_value"
            } else {
                "value"
            };
            body.push_str(&format!(
                "        Ok({}) => Ok({}),\n",
                value_name,
                encode_value("value", &binding.return_type, collector)
            ));
        }
        if collector.uses_zova_errors() && err_name == "Error" {
            body.push_str("        Err(err) => Err(__kiro_zova_error(err)),\n");
        } else {
            body.push_str(&format!(
                "        Err(err) => Err(KiroError::message(\"{}\", err.to_string())),\n",
                err_name
            ));
        }
        body.push_str("    }\n");
    } else {
        if let Some(buffer) = &binding.output_buffer {
            body.push_str(&format!("    let copied = {};\n", call));
            body.push_str(&format!(
                "    if copied > {buffer}.len() {{ return Err(KiroError::message(\"HostContractError\", \"host wrote beyond its output buffer\")); }}\n    {buffer}.truncate(copied);\n    Ok(RuntimeVal::bytes({buffer}))\n"
            ));
        } else {
            match binding.return_type {
                RustType::Void => {
                    body.push_str(&format!("    {};\n", call));
                    body.push_str("    Ok(RuntimeVal::Void)\n");
                }
                _ => {
                    body.push_str(&format!("    let value = {};\n", call));
                    body.push_str(&format!(
                        "    Ok({})\n",
                        encode_value("value", &binding.return_type, collector)
                    ));
                }
            }
        }
    }
    body.push_str("}\n");
    body
}

fn call_argument(param: &Param) -> String {
    if param.rust_type == RustType::OutputBuffer {
        format!("&mut {}", param.rust_name)
    } else {
        param.rust_name.clone()
    }
}

fn binding_uses_one_shot_receiver(binding: &Binding, collector: &Collector) -> bool {
    let BindingSource::Method { .. } = binding.source else {
        return false;
    };
    matches!(
        binding.params.first().map(|param| &param.rust_type),
        Some(RustType::Handle(type_name)) if collector.is_one_shot_handle(type_name)
    )
}

fn decode_param(
    binding: &Binding,
    idx: usize,
    param: &Param,
    fn_name: &str,
    collector: &Collector,
) -> String {
    let arg = format!("RuntimeVal::expect_arg(&args, {}, \"{}\")?", idx, fn_name);
    let name = &param.rust_name;
    match &param.rust_type {
        RustType::Str { borrowed: true } => {
            format!("    let {} = {}.as_str()?;\n", name, arg)
        }
        RustType::Str { borrowed: false } => {
            format!("    let {} = {}.as_str()?.to_string();\n", name, arg)
        }
        RustType::Bytes { borrowed: true } => {
            format!("    let {} = {}.as_bytes()?;\n", name, arg)
        }
        RustType::Bytes { borrowed: false } => {
            format!("    let {} = {}.as_bytes()?.to_vec();\n", name, arg)
        }
        RustType::Num { rust } if rust == "f64" => {
            format!("    let {} = {}.as_num()?;\n", name, arg)
        }
        RustType::Num { rust } if rust == "f32" => {
            format!("    let {} = {}.as_num()? as f32;\n", name, arg)
        }
        RustType::Num { rust } => {
            format!("    let {} = {}.as_num()? as {};\n", name, arg, rust)
        }
        RustType::Bool => format!("    let {} = {}.as_bool()?;\n", name, arg),
        RustType::StringEnum(type_name) => decode_enum_param(name, &arg, type_name, collector),
        RustType::VectorValues { owned: false } => {
            decode_vector_values_param(name, &arg, collector)
        }
        RustType::VectorValues { owned: true } => format!(
            "    let {} = {};\n",
            name,
            decode_owned_vector_values_expr(&arg, collector)
        ),
        RustType::OutputBuffer => format!(
            "    let __kiro_length = {}.as_num()?;\n    if !__kiro_length.is_finite() || __kiro_length < 0.0 || __kiro_length.fract() != 0.0 || __kiro_length > usize::MAX as f64 {{ return Err(KiroError::message(\"InvalidRange\", \"length must be a non-negative integer\")); }}\n    let mut {} = vec![0u8; __kiro_length as usize];\n",
            arg, name
        ),
        RustType::Record {
            name: type_name, ..
        } => decode_record_param(name, &arg, type_name, collector),
        RustType::Handle(type_name)
            if idx == 0
                && matches!(binding.source, BindingSource::Method { .. })
                && collector.is_one_shot_handle(type_name) =>
        {
            let (receiver_consuming, receiver_mutable) = match binding.source {
                BindingSource::Method {
                    receiver_consuming,
                    receiver_mutable,
                    ..
                } => (receiver_consuming, receiver_mutable),
                _ => unreachable!(),
            };
            let guard = format!("__kiro_{}_guard", name);
            let access = if receiver_consuming {
                "take()"
            } else if receiver_mutable {
                "as_mut()"
            } else {
                "as_ref()"
            };
            format!(
                "    let mut {guard} = {arg}.as_handle(\"{type_name}\")?.downcast_ref::<std::sync::Mutex<Option<{payload}>>>().ok_or_else(|| KiroError::message(\"TypeError\", \"expected consumable handle payload {type_name}\"))?.lock().map_err(|_| KiroError::message(\"HandlePoisoned\", \"{type_name} handle lock was poisoned\"))?;\n    let {name} = {guard}.{access}.ok_or_else(|| KiroError::message(\"HandleConsumed\", \"{type_name} handle was already consumed\"))?;\n",
                payload = handle_payload_type(binding, type_name),
            )
        }
        RustType::Handle(type_name)
            if idx == 0 && matches!(binding.source, BindingSource::Method { .. }) =>
        {
            let mutable = matches!(
                binding.source,
                BindingSource::Method {
                    receiver_mutable: true,
                    ..
                }
            ) && idx == 0;
            if collector.mutable_handles.contains(type_name) {
                let mutability = if mutable { "mut " } else { "" };
                format!(
                    "    let {mutability}{} = {}.as_handle(\"{}\")?.downcast_ref::<std::sync::Mutex<{}>>().ok_or_else(|| KiroError::message(\"TypeError\", \"expected mutable handle payload {}\"))?.lock().map_err(|_| KiroError::message(\"HandlePoisoned\", \"{} handle lock was poisoned\"))?;\n",
                    name,
                    arg,
                    type_name,
                    handle_payload_type(binding, type_name),
                    type_name,
                    type_name
                )
            } else {
                format!(
                    "    let {} = {}.as_handle(\"{}\")?.downcast_ref::<{}>().ok_or_else(|| KiroError::message(\"TypeError\", \"expected handle payload {}\"))?;\n",
                    name,
                    arg,
                    type_name,
                    handle_payload_type(binding, type_name),
                    type_name
                )
            }
        }
        RustType::Handle(type_name)
            if collector.copy_handles.contains(type_name)
                && collector.mutable_handles.contains(type_name) =>
        {
            format!(
                "    let {} = *{}.as_handle(\"{}\")?.downcast_ref::<std::sync::Mutex<{}>>().ok_or_else(|| KiroError::message(\"TypeError\", \"expected mutable handle payload {}\"))?.lock().map_err(|_| KiroError::message(\"HandlePoisoned\", \"{} handle lock was poisoned\"))?;\n",
                name,
                arg,
                type_name,
                handle_payload_type(binding, type_name),
                type_name,
                type_name
            )
        }
        RustType::Handle(type_name) if collector.copy_handles.contains(type_name) => {
            format!(
                "    let {} = *{}.as_handle(\"{}\")?.downcast_ref::<{}>().ok_or_else(|| KiroError::message(\"TypeError\", \"expected handle payload {}\"))?;\n",
                name,
                arg,
                type_name,
                handle_payload_type(binding, type_name),
                type_name
            )
        }
        RustType::Handle(type_name) if collector.mutable_handles.contains(type_name) => {
            format!(
                "    let {} = {}.as_handle(\"{}\")?.downcast_ref::<std::sync::Mutex<{}>>().ok_or_else(|| KiroError::message(\"TypeError\", \"expected mutable handle payload {}\"))?.lock().map_err(|_| KiroError::message(\"HandlePoisoned\", \"{} handle lock was poisoned\"))?;\n",
                name,
                arg,
                type_name,
                handle_payload_type(binding, type_name),
                type_name,
                type_name
            )
        }
        RustType::Handle(type_name) => format!(
            "    let {} = {}.as_handle(\"{}\")?.downcast_ref::<{}>().ok_or_else(|| KiroError::message(\"TypeError\", \"expected handle payload {}\"))?;\n",
            name,
            arg,
            type_name,
            handle_payload_type(binding, type_name),
            type_name
        ),
        RustType::List(inner) => decode_list_param(name, &arg, inner, collector),
        RustType::Map(inner) => decode_map_param(name, &arg, inner, collector),
        RustType::Void => format!("    let {} = ();\n", name),
    }
}

fn decode_list_param(name: &str, arg: &str, inner: &RustType, collector: &Collector) -> String {
    let mut out = format!("    let mut {} = Vec::new();\n", name);
    out.push_str(&format!("    for item in {}.as_list()? {{\n", arg));
    out.push_str(&format!(
        "        {}.push({});\n",
        name,
        decode_runtime_expr("item", inner, collector)
    ));
    out.push_str("    }\n");
    out
}

fn decode_map_param(name: &str, arg: &str, inner: &RustType, collector: &Collector) -> String {
    let mut out = format!("    let mut {} = std::collections::HashMap::new();\n", name);
    out.push_str(&format!("    for (key, value) in {}.as_map()? {{\n", arg));
    out.push_str(&format!(
        "        {}.insert(key.clone(), {});\n",
        name,
        decode_runtime_expr("value", inner, collector)
    ));
    out.push_str("    }\n");
    out
}

fn decode_enum_param(name: &str, arg: &str, type_name: &str, collector: &Collector) -> String {
    format!(
        "    let {} = {};\n",
        name,
        decode_enum_expr(arg, type_name, collector)
    )
}

fn decode_enum_expr(value: &str, type_name: &str, collector: &Collector) -> String {
    let enum_def = collector
        .simple_enums
        .get(type_name)
        .expect("simple enum Rust type must have a definition");
    let arms = enum_def
        .variants
        .iter()
        .map(|variant| {
            format!(
                "\"{}\" => {}::{}::{},",
                to_snake_case(variant),
                collector.crate_ident,
                type_name,
                variant
            )
        })
        .collect::<Vec<_>>()
        .join(" ");
    let accepted = enum_def
        .variants
        .iter()
        .map(|variant| to_snake_case(variant))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "match {}.as_str()? {{ {} value => return Err(KiroError::message(\"Invalid{}\", format!(\"expected one of [{}], got '{{}}'\", value))) }}",
        value, arms, type_name, accepted
    )
}

fn decode_vector_values_param(name: &str, arg: &str, collector: &Collector) -> String {
    format!(
        "    let __kiro_vector_fields = {arg}.as_struct(\"VectorValues\")?;\n    let __kiro_element_type = __kiro_vector_fields.get(\"element_type\").ok_or_else(|| KiroError::message(\"TypeError\", \"missing VectorValues.element_type\"))?.as_str()?;\n    let __kiro_values = __kiro_vector_fields.get(\"values\").ok_or_else(|| KiroError::message(\"TypeError\", \"missing VectorValues.values\"))?.as_list()?;\n    let mut __kiro_f32_values = Vec::new();\n    let mut __kiro_f16_values = Vec::new();\n    let mut __kiro_i8_values = Vec::new();\n    match __kiro_element_type {{\n        \"f32\" => for item in __kiro_values {{ __kiro_f32_values.push(item.as_num()? as f32); }},\n        \"f16\" => for item in __kiro_values {{ __kiro_f16_values.push(__kiro_f32_to_f16_bits(item.as_num()? as f32)); }},\n        \"i8\" => for item in __kiro_values {{ let value = item.as_num()?; if !value.is_finite() || value.fract() != 0.0 || value < i8::MIN as f64 || value > i8::MAX as f64 {{ return Err(KiroError::message(\"InvalidVectorValue\", \"i8 vector values must be integers from -128 through 127\")); }} __kiro_i8_values.push(value as i8); }},\n        value => return Err(KiroError::message(\"InvalidVectorElementType\", format!(\"expected f32, f16, or i8, got '{{}}'\", value))),\n    }}\n    let {name} = match __kiro_element_type {{\n        \"f32\" => {crate_name}::VectorValues::F32(&__kiro_f32_values),\n        \"f16\" => {crate_name}::VectorValues::F16(&__kiro_f16_values),\n        \"i8\" => {crate_name}::VectorValues::I8(&__kiro_i8_values),\n        _ => unreachable!(),\n    }};\n",
        crate_name = collector.crate_ident
    )
}

fn decode_owned_vector_values_expr(value: &str, collector: &Collector) -> String {
    format!(
        "{{ let fields = {value}.as_struct(\"VectorValues\")?; let element_type = fields.get(\"element_type\").ok_or_else(|| KiroError::message(\"TypeError\", \"missing VectorValues.element_type\"))?.as_str()?; let values = fields.get(\"values\").ok_or_else(|| KiroError::message(\"TypeError\", \"missing VectorValues.values\"))?.as_list()?; match element_type {{ \"f32\" => {crate_name}::VectorValuesOwned::F32(values.iter().map(|item| Ok(item.as_num()? as f32)).collect::<Result<Vec<_>, KiroError>>()?), \"f16\" => {crate_name}::VectorValuesOwned::F16(values.iter().map(|item| Ok(__kiro_f32_to_f16_bits(item.as_num()? as f32))).collect::<Result<Vec<_>, KiroError>>()?), \"i8\" => {{ let mut decoded = Vec::with_capacity(values.len()); for item in values {{ let value = item.as_num()?; if !value.is_finite() || value.fract() != 0.0 || value < i8::MIN as f64 || value > i8::MAX as f64 {{ return Err(KiroError::message(\"InvalidVectorValue\", \"i8 vector values must be integers from -128 through 127\")); }} decoded.push(value as i8); }} {crate_name}::VectorValuesOwned::I8(decoded) }}, value => return Err(KiroError::message(\"InvalidVectorElementType\", format!(\"expected f32, f16, or i8, got '{{}}'\", value))) }} }}",
        crate_name = collector.crate_ident
    )
}

fn decode_runtime_expr(value: &str, ty: &RustType, collector: &Collector) -> String {
    match ty {
        RustType::Str { borrowed: true } => format!("{}.as_str()?", value),
        RustType::Str { borrowed: false } => format!("{}.as_str()?.to_string()", value),
        RustType::Bytes { borrowed: true } => format!("{}.as_bytes()?", value),
        RustType::Bytes { borrowed: false } => format!("{}.as_bytes()?.to_vec()", value),
        RustType::Num { rust } if rust == "f64" => format!("{}.as_num()?", value),
        RustType::Num { rust } => format!("{}.as_num()? as {}", value, rust),
        RustType::Bool => format!("{}.as_bool()?", value),
        RustType::StringEnum(type_name) => decode_enum_expr(value, type_name, collector),
        RustType::VectorValues { owned: true } => decode_owned_vector_values_expr(value, collector),
        RustType::Record {
            name: type_name, ..
        } => decode_record_expr(value, type_name, collector),
        _ => {
            "return Err(KiroError::message(\"TypeError\", \"unsupported nested type\"))".to_string()
        }
    }
}

fn decode_record_param(name: &str, arg: &str, type_name: &str, collector: &Collector) -> String {
    format!(
        "    let {} = {};\n",
        name,
        decode_record_expr(arg, type_name, collector)
    )
}

fn decode_record_expr(value: &str, type_name: &str, collector: &Collector) -> String {
    let record = collector
        .records
        .get(type_name)
        .expect("record Rust type must have a definition");
    let fields = record
        .fields
        .iter()
        .map(|field| {
            let value = format!(
                "__kiro_fields.get(\"{}\").ok_or_else(|| KiroError::message(\"TypeError\", \"missing {}.{}\"))?",
                field.name, type_name, field.name
            );
            format!(
                "{}: {}",
                field.name,
                decode_runtime_expr(&value, &field.rust_type, collector)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "{{ let __kiro_fields = {}.as_struct(\"{}\")?; {}::{} {{ {} }} }}",
        value, type_name, collector.crate_ident, type_name, fields
    )
}

fn encode_value(name: &str, ty: &RustType, collector: &Collector) -> String {
    match ty {
        RustType::Void => "RuntimeVal::Void".to_string(),
        RustType::Handle(type_name) if collector.is_one_shot_handle(type_name) => format!(
            "RuntimeVal::handle(\"{}\", std::sync::Mutex::new(Some({})))",
            type_name, name
        ),
        RustType::Handle(type_name) if collector.mutable_handles.contains(type_name) => format!(
            "RuntimeVal::handle(\"{}\", std::sync::Mutex::new({}))",
            type_name, name
        ),
        RustType::Handle(type_name) => format!("RuntimeVal::handle(\"{}\", {})", type_name, name),
        _ => encode_inner_value(name, ty, collector),
    }
}

fn encode_inner_value(name: &str, ty: &RustType, collector: &Collector) -> String {
    match ty {
        RustType::Str { .. } | RustType::Bool => format!("RuntimeVal::from({})", name),
        RustType::Bytes { .. } => format!("RuntimeVal::bytes({})", name),
        RustType::Num { .. } => format!("RuntimeVal::from({} as f64)", name),
        RustType::StringEnum(type_name) => encode_enum_value(name, type_name, collector),
        RustType::VectorValues { .. } => encode_vector_values(name, collector),
        RustType::List(inner) => format!(
            "RuntimeVal::List({}.into_iter().map(|v| {}).collect())",
            name,
            encode_inner_value("v", inner, collector)
        ),
        RustType::Map(inner) => format!(
            "RuntimeVal::Map({}.into_iter().map(|(k, v)| (k, {})).collect())",
            name,
            encode_inner_value("v", inner, collector)
        ),
        RustType::Record {
            name: type_name, ..
        } => {
            let record = collector
                .records
                .get(type_name)
                .expect("record Rust type must have a definition");
            let fields = record
                .fields
                .iter()
                .map(|field| {
                    format!(
                        "(\"{}\".to_string(), {})",
                        field.name,
                        encode_inner_value(
                            &format!("{}.{}", name, field.name),
                            &field.rust_type,
                            collector,
                        )
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!(
                "RuntimeVal::structure(\"{}\", [{}].into_iter().collect())",
                type_name, fields
            )
        }
        RustType::Handle(type_name) => format!("RuntimeVal::handle(\"{}\", {})", type_name, name),
        RustType::Void | RustType::OutputBuffer => "RuntimeVal::Void".to_string(),
    }
}

fn encode_enum_value(name: &str, type_name: &str, collector: &Collector) -> String {
    let enum_def = collector
        .simple_enums
        .get(type_name)
        .expect("simple enum Rust type must have a definition");
    let arms = enum_def
        .variants
        .iter()
        .map(|variant| {
            format!(
                "{}::{}::{} => RuntimeVal::from(\"{}\"),",
                collector.crate_ident,
                type_name,
                variant,
                to_snake_case(variant)
            )
        })
        .collect::<Vec<_>>()
        .join(" ");
    format!("match {} {{ {} }}", name, arms)
}

fn encode_vector_values(name: &str, collector: &Collector) -> String {
    format!(
        "match {name} {{ {crate_name}::VectorValuesOwned::F32(values) => RuntimeVal::structure(\"VectorValues\", [(\"element_type\".to_string(), RuntimeVal::from(\"f32\")), (\"values\".to_string(), RuntimeVal::List(values.into_iter().map(|value| RuntimeVal::from(value as f64)).collect()))].into_iter().collect()), {crate_name}::VectorValuesOwned::F16(values) => RuntimeVal::structure(\"VectorValues\", [(\"element_type\".to_string(), RuntimeVal::from(\"f16\")), (\"values\".to_string(), RuntimeVal::List(values.into_iter().map(|value| RuntimeVal::from(__kiro_f16_bits_to_f32(value) as f64)).collect()))].into_iter().collect()), {crate_name}::VectorValuesOwned::I8(values) => RuntimeVal::structure(\"VectorValues\", [(\"element_type\".to_string(), RuntimeVal::from(\"i8\")), (\"values\".to_string(), RuntimeVal::List(values.into_iter().map(|value| RuntimeVal::from(value as f64)).collect()))].into_iter().collect()) }}",
        crate_name = collector.crate_ident
    )
}

fn kiro_type(ty: &RustType) -> String {
    match ty {
        RustType::Str { .. } => "str".to_string(),
        RustType::Bytes { .. } => "bytes".to_string(),
        RustType::Num { .. } => "num".to_string(),
        RustType::Bool => "bool".to_string(),
        RustType::Void => "void".to_string(),
        RustType::List(inner) => format!("list {}", kiro_type(inner)),
        RustType::Map(inner) => format!("map str {}", kiro_type(inner)),
        RustType::StringEnum(_) => "str".to_string(),
        RustType::VectorValues { .. } => "VectorValues".to_string(),
        RustType::OutputBuffer => "num".to_string(),
        RustType::Record { name, .. } | RustType::Handle(name) => name.clone(),
    }
}

pub(super) fn initial_rust_module(manual_module: &str) -> String {
    format!(
        r#"mod {manual_module} {{
    use super::*;
    use kiro_macros::{{kiro_export, kiro_handle, kiro_struct}};
    use std::collections::HashMap;
}}

// kiro:generated begin
// kiro:generated end
"#
    )
}

pub(super) fn replace_generated_region(existing: &str, generated: &str) -> String {
    let Some(start) = existing.find(GENERATED_BEGIN) else {
        let mut out = existing.trim_end().to_string();
        out.push_str("\n\n");
        out.push_str(generated);
        return out;
    };
    let Some(end_rel) = existing[start..].find(GENERATED_END) else {
        let mut out = existing[..start].trim_end().to_string();
        out.push_str("\n\n");
        out.push_str(generated);
        return out;
    };
    let end = start + end_rel + GENERATED_END.len();
    let mut out = String::new();
    out.push_str(existing[..start].trim_end());
    out.push_str("\n\n");
    out.push_str(generated.trim_end());
    out.push('\n');
    out.push_str(existing[end..].trim_start_matches('\n'));
    out
}

const ZOVA_ERROR_HELPER: &str = r#"fn __kiro_zova_error(err: zova::Error) -> KiroError {
    let name = match err.status() {
        Some(zova::Status::Busy) => "ZovaBusy".to_string(),
        Some(status) => {
            let mut name = String::from("Zova");
            for word in status.name().strip_prefix("ZOVA_").unwrap_or("ERROR").split('_') {
                let mut chars = word.chars();
                if let Some(first) = chars.next() {
                    name.extend(first.to_uppercase());
                    name.extend(chars.flat_map(char::to_lowercase));
                }
            }
            name
        }
        None => "ZovaError".to_string(),
    };
    KiroError::message(&name, err.to_string())
}
"#;

const VECTOR_VALUE_HELPERS: &str = r#"fn __kiro_f32_to_f16_bits(value: f32) -> u16 {
    let bits = value.to_bits();
    let sign = ((bits >> 16) & 0x8000) as u16;
    let exponent = ((bits >> 23) & 0xff) as i32 - 127 + 15;
    let mantissa = bits & 0x7fffff;
    if exponent <= 0 {
        if exponent < -10 {
            return sign;
        }
        let mantissa = mantissa | 0x800000;
        let shift = 14 - exponent;
        let rounded = (mantissa + (1 << (shift - 1))) >> shift;
        return sign | rounded as u16;
    }
    if exponent >= 31 {
        return sign | if mantissa == 0 { 0x7c00 } else { 0x7e00 };
    }
    let rounded = mantissa + 0x1000;
    if rounded & 0x800000 != 0 {
        let next_exponent = exponent + 1;
        return sign | if next_exponent >= 31 { 0x7c00 } else { (next_exponent as u16) << 10 };
    }
    sign | ((exponent as u16) << 10) | ((rounded >> 13) as u16)
}

fn __kiro_f16_bits_to_f32(value: u16) -> f32 {
    let sign = ((value & 0x8000) as u32) << 16;
    let exponent = ((value >> 10) & 0x1f) as u32;
    let mantissa = (value & 0x03ff) as u32;
    let bits = match exponent {
        0 if mantissa == 0 => sign,
        0 => {
            let mut mantissa = mantissa;
            let mut exponent = 113u32;
            while mantissa & 0x0400 == 0 {
                mantissa <<= 1;
                exponent -= 1;
            }
            sign | (exponent << 23) | ((mantissa & 0x03ff) << 13)
        }
        31 => sign | 0x7f800000 | (mantissa << 13),
        _ => sign | ((exponent + 112) << 23) | (mantissa << 13),
    };
    f32::from_bits(bits)
}
"#;
